spring:
  application:
    name: WebShop
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/webshopproject
    username: postgres
    password: 1234

token:
  time-to-live: 12000000
  secret: DFBhMoJyUmkPdDyfZ5RdYq57rlfnWMUEoqLXV195yWQrNnAD7ZzRD1fRYM9XzHzH9I361QDgh7usZXwrOIV3+A==